name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Install web deps
        working-directory: apps/web
        run: npm ci

      - name: Build web
        working-directory: apps/web
        run: npm run build

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build API
        working-directory: apps/api
        run: dotnet build --configuration Release

      - name: Build Functions
        working-directory: apps/functions
        run: dotnet build --configuration Release

      - name: Placeholder tests
        run: echo "E2E and unit tests to be added next."
