name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Placeholder build
        run: |
          echo "No apps scaffolded yet. Skipping builds."
      - name: Placeholder tests
        run: |
          echo "No tests yet."
