name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy (dev|staging|prod)"
        required: true
        default: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy placeholder
        run: |
          echo "Deploying to ${{ github.event.inputs.env }} (placeholder)"
