name: Infra

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to provision/update (dev|staging|prod)"
        required: true
        default: dev

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Infra placeholder
        run: |
          echo "Provisioning infra for ${{ github.event.inputs.env }} (placeholder)"
